mysql:
  host: 192.168.0.161
  port: 3306
  user: root
  password: 123456
  dbname: licslan
  max_open_conns: 30
  max_idle_conns: 2



redis:
  host: 192.168.0.161
  port: 6380
  db: 0
  pool_size: 100



log:
  level: debugger
  filename: "./log/licslan.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5